Repository BuildForSDGCohort2/Team-254-zaoBora-backend, pull requests merged in 2020-09, with the labels that each got.

#7 ✏ Authentication, Endpoints, Database setup and requirements.txt
  .gitignore
  README.md
  app/__init__.py
  app/api/__init__.py
  app/api/v1/__init__.py
  app/api/v1/models/base_model.py
  app/api/v1/models/user_model.py
  app/api/v1/utils/response.py
  app/api/v1/utils/users_validator.py
  app/api/v1/views/user_view.py
  app/database.py
  requirements.txt
  run.py
Labels: enhancement

#11 Ft mpesa endpoint
  Procfile
  app/__init__.py
  app/api/v1/utils/keys.py
  app/api/v1/utils/transact_mpesa.py
  app/api/v1/views/user_view.py
  app/database.py
  requirements.txt
Labels: enhancement

#14 Modified requirements.txt file
  app/api/v1/utils/transact_mpesa.py
  app/api/v1/views/product_view.py
  app/api/v1/views/vendor_view.py
  app/database.py
  requirements.txt
Labels: bug

#15 Fixed Readme file and db connection flow
  .env.example
  README.md
  app/__init__.py
  app/database.py
  config/__init__.py
  config/default.py
  config/development.py
  config/production.py
  config/staging.py
  config/testing.py
  requirements.txt
  run.py
Labels: documentation

#16 Ch modify table fields
  .env.example
  README.md
  app/api/v1/models/base_model.py
  app/api/v1/models/user_model.py
  app/api/v1/utils/response.py
  app/api/v1/utils/users_validator.py
  app/api/v1/views/user_view.py
  app/database.py
  config/development.py
  requirements.txt
Labels: enhancement

#17 Fixed vendor endpoints
  Procfile
  README.md
  app/__init__.py
  app/api/v1/models/base_model.py
  app/api/v1/models/product_model.py
  app/api/v1/models/user_model.py
  app/api/v1/models/vendor_model.py
  app/api/v1/utils/transact_mpesa.py
  app/api/v1/utils/users_validator.py
  app/api/v1/views/order_view.py
  app/api/v1/views/product_view.py
  app/api/v1/views/user_view.py
  app/api/v1/views/vendor_view.py
  app/database.py
  config/development.py
  config/production.py
  requirements.txt
Labels: enhancement

#20 Built email verification with flask-mail
  .env.example
  README.md
  app/__init__.py
  app/api/v1/models/user_model.py
  app/api/v1/views/user_view.py
  app/database.py
  config/default.py
  config/development.py
  requirements.txt
Labels: documentation

#18 Sms notification endpoint
  .env.example
  app/api/v1/utils/keys.py
  app/api/v1/utils/phone_nofications.py
  app/api/v1/utils/transact_mpesa.py
  app/database.py
  config/development.py
  requirements.txt
  run.py
Labels: bug

#22 Finished email authentication
  app/__init__.py
  app/api/v1/models/user_model.py
  app/api/v1/models/vendor_model.py
  app/api/v1/utils/email.py
  app/api/v1/views/user_view.py
  app/api/v1/views/vendor_view.py
Labels: documentation, enhancement
